#!/bin/bash

set -eu

test -n "${CLI_API_KEY}"

PRIVATE_KEY_FILE="/keys/id_rsa"
PUBLIC_KEY_FILE="/keys/id_rsa.pub"

while [ ! -f "${PUBLIC_KEY_FILE}" ]
do
    echo "Waiting for keys to be generated by collector ..."
    sleep 5
done

KEY_COMMENT="$(awk '{print $3}' <"${PUBLIC_KEY_FILE}")"

eval "$(ssh-agent -s)"
ssh-add "${PRIVATE_KEY_FILE}"

# login to balena with provided api key
balena login --token "${CLI_API_KEY}"

# remove any existing public key with this comment
balena key rm "$(balena keys | grep "${KEY_COMMENT}" | awk '{print $1}')" --yes 2>/dev/null || true

# add public rsa key to balena cloud
balena key add "${KEY_COMMENT}" "${PUBLIC_KEY_FILE}"

PRIVATE_KEY="$(<${PRIVATE_KEY_FILE})"
export PRIVATE_KEY

exec "$@"
